-- Services layer, professional credentials, profile modality flags,
-- drop profile-level radius and raw location_input_text; recreate search view.

-- 1) Helper: listable professional (SECURITY DEFINER + row_security off for RLS-safe checks)
create or replace function public.is_professional_publicly_listable(pro_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select exists (
    select 1
    from public.users u
    inner join public.professional_search_profiles p on p.user_id = u.id
    where u.id = pro_id
      and coalesce(u.is_professional, false) = true
      and p.is_profile_complete = true
      and p.is_public_searchable = true
      and p.is_active = true
      and p.is_approved = true
  );
$$;

comment on function public.is_professional_publicly_listable(bigint) is
  'True when the professional appears in public search; used by RLS on services-related tables.';

revoke all on function public.is_professional_publicly_listable(bigint) from public;
grant execute on function public.is_professional_publicly_listable(bigint) to anon, authenticated;

-- 2) Drop dependent view before altering professional_search_profiles
drop view if exists public.professional_search_cards_enriched;

-- 3) professional_search_profiles: modality flags, remove legacy geo columns
alter table public.professional_search_profiles
  add column if not exists offers_remote boolean not null default false,
  add column if not exists offers_in_home boolean not null default false,
  add column if not exists offers_provider_location boolean not null default false;

alter table public.professional_search_profiles
  drop column if exists service_radius_km,
  drop column if exists location_input_text;

comment on table public.professional_search_profiles is
  'Professional listing visibility, Mapbox-backed base location, and high-level delivery modality flags.';

-- 4) services
create table public.services (
  id bigint generated by default as identity primary key,
  professional_id bigint not null references public.users (id) on delete cascade,
  specialty_id bigint references public.specialties (id) on delete set null,
  title text not null,
  description text,
  price_cents integer,
  currency_code text not null default 'GBP',
  duration_minutes integer,
  delivery_mode text not null,
  remote_scope text,
  provider_location_name text,
  service_area_type text,
  service_radius_km numeric(6, 2),
  service_area_text text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint services_currency_code_len check (char_length(trim(currency_code)) = 3),
  constraint services_delivery_mode_check check (
    delivery_mode in ('remote', 'in_home', 'provider_location', 'hybrid')
  ),
  constraint services_remote_scope_check check (
    remote_scope is null
    or remote_scope in ('anywhere', 'country', 'region', 'custom')
  ),
  constraint services_service_area_type_check check (
    service_area_type is null
    or service_area_type in ('radius', 'place_list', 'custom_text')
  ),
  constraint services_price_cents_non_negative check (
    price_cents is null or price_cents >= 0
  ),
  constraint services_duration_non_negative check (
    duration_minutes is null or duration_minutes >= 0
  )
);

create index services_professional_id_idx on public.services (professional_id);
create index services_professional_active_idx on public.services (professional_id)
  where is_active = true;

create or replace function public.services_set_updated_at()
returns trigger
language plpgsql
as $fn$
begin
  new.updated_at := now();
  return new;
end;
$fn$;

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at
  before update on public.services
  for each row execute function public.services_set_updated_at();

alter table public.services enable row level security;

grant select on table public.services to anon, authenticated;
grant insert, update, delete on table public.services to authenticated;

drop policy if exists "services_select_own" on public.services;
create policy "services_select_own"
  on public.services
  for select
  to authenticated
  using (professional_id = public.app_user_id_for_auth());

drop policy if exists "services_select_public" on public.services;
create policy "services_select_public"
  on public.services
  for select
  to anon, authenticated
  using (
    is_active = true
    and public.is_professional_publicly_listable(professional_id)
  );

drop policy if exists "services_insert_own" on public.services;
create policy "services_insert_own"
  on public.services
  for insert
  to authenticated
  with check (professional_id = public.app_user_id_for_auth());

drop policy if exists "services_update_own" on public.services;
create policy "services_update_own"
  on public.services
  for update
  to authenticated
  using (professional_id = public.app_user_id_for_auth())
  with check (professional_id = public.app_user_id_for_auth());

drop policy if exists "services_delete_own" on public.services;
create policy "services_delete_own"
  on public.services
  for delete
  to authenticated
  using (professional_id = public.app_user_id_for_auth());

-- 5) service_provider_locations
create table public.service_provider_locations (
  id bigint generated by default as identity primary key,
  service_id bigint not null references public.services (id) on delete cascade,
  location_name text,
  country_code text not null default 'GB',
  location_label text,
  mapbox_id text,
  latitude double precision,
  longitude double precision,
  geocoded_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

create index service_provider_locations_service_id_idx
  on public.service_provider_locations (service_id);

alter table public.service_provider_locations enable row level security;

grant select on table public.service_provider_locations to anon, authenticated;
grant insert, update, delete on table public.service_provider_locations to authenticated;

drop policy if exists "service_provider_locations_select_own" on public.service_provider_locations;
create policy "service_provider_locations_select_own"
  on public.service_provider_locations
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  );

drop policy if exists "service_provider_locations_select_public" on public.service_provider_locations;
create policy "service_provider_locations_select_public"
  on public.service_provider_locations
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.is_active = true
        and public.is_professional_publicly_listable(s.professional_id)
    )
  );

drop policy if exists "service_provider_locations_insert_own" on public.service_provider_locations;
create policy "service_provider_locations_insert_own"
  on public.service_provider_locations
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  );

drop policy if exists "service_provider_locations_update_own" on public.service_provider_locations;
create policy "service_provider_locations_update_own"
  on public.service_provider_locations
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  )
  with check (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  );

drop policy if exists "service_provider_locations_delete_own" on public.service_provider_locations;
create policy "service_provider_locations_delete_own"
  on public.service_provider_locations
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  );

-- 6) service_area_places
create table public.service_area_places (
  id bigint generated by default as identity primary key,
  service_id bigint not null references public.services (id) on delete cascade,
  country_code text not null default 'GB',
  location_label text,
  mapbox_id text,
  latitude double precision,
  longitude double precision,
  geocoded_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

create index service_area_places_service_id_idx on public.service_area_places (service_id);

alter table public.service_area_places enable row level security;

grant select on table public.service_area_places to anon, authenticated;
grant insert, update, delete on table public.service_area_places to authenticated;

drop policy if exists "service_area_places_select_own" on public.service_area_places;
create policy "service_area_places_select_own"
  on public.service_area_places
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  );

drop policy if exists "service_area_places_select_public" on public.service_area_places;
create policy "service_area_places_select_public"
  on public.service_area_places
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.is_active = true
        and public.is_professional_publicly_listable(s.professional_id)
    )
  );

drop policy if exists "service_area_places_insert_own" on public.service_area_places;
create policy "service_area_places_insert_own"
  on public.service_area_places
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  );

drop policy if exists "service_area_places_update_own" on public.service_area_places;
create policy "service_area_places_update_own"
  on public.service_area_places
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  )
  with check (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  );

drop policy if exists "service_area_places_delete_own" on public.service_area_places;
create policy "service_area_places_delete_own"
  on public.service_area_places
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.services s
      where s.id = service_id
        and s.professional_id = public.app_user_id_for_auth()
    )
  );

-- 7) professional_credentials
create table public.professional_credentials (
  id bigint generated by default as identity primary key,
  professional_id bigint not null references public.users (id) on delete cascade,
  credential_type text not null,
  credential_label text not null,
  issuing_body text,
  registration_number text,
  verification_status text not null default 'unverified',
  expires_at date,
  verified_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  constraint professional_credentials_verification_status_check check (
    verification_status in ('unverified', 'pending', 'verified', 'rejected')
  )
);

create index professional_credentials_professional_id_idx
  on public.professional_credentials (professional_id);

alter table public.professional_credentials enable row level security;

grant select on table public.professional_credentials to anon, authenticated;
grant insert, update, delete on table public.professional_credentials to authenticated;

drop policy if exists "professional_credentials_select_own" on public.professional_credentials;
create policy "professional_credentials_select_own"
  on public.professional_credentials
  for select
  to authenticated
  using (professional_id = public.app_user_id_for_auth());

drop policy if exists "professional_credentials_select_public" on public.professional_credentials;
create policy "professional_credentials_select_public"
  on public.professional_credentials
  for select
  to anon, authenticated
  using (public.is_professional_publicly_listable(professional_id));

drop policy if exists "professional_credentials_insert_own" on public.professional_credentials;
create policy "professional_credentials_insert_own"
  on public.professional_credentials
  for insert
  to authenticated
  with check (professional_id = public.app_user_id_for_auth());

drop policy if exists "professional_credentials_update_own" on public.professional_credentials;
create policy "professional_credentials_update_own"
  on public.professional_credentials
  for update
  to authenticated
  using (professional_id = public.app_user_id_for_auth())
  with check (professional_id = public.app_user_id_for_auth());

drop policy if exists "professional_credentials_delete_own" on public.professional_credentials;
create policy "professional_credentials_delete_own"
  on public.professional_credentials
  for delete
  to authenticated
  using (professional_id = public.app_user_id_for_auth());

-- 8) Recreate professional_search_cards_enriched
create view public.professional_search_cards_enriched
with (security_invoker = true) as
select
  u.id as professional_id,
  u.first_name,
  u.last_name,
  u.profile_photo_url,
  u.bio,
  p.country_code,
  p.location_label,
  p.mapbox_id,
  p.latitude,
  p.longitude,
  p.offers_remote,
  p.offers_in_home,
  p.offers_provider_location,
  coalesce(
    array_agg(distinct s.label) filter (where s.label is not null),
    array[]::text[]
  ) as specialties
from public.users u
inner join public.professional_search_profiles p
  on p.user_id = u.id
left join public.professional_specialties ps
  on ps.professional_id = u.id
left join public.specialties s
  on s.id = ps.specialty_id
where coalesce(u.is_professional, false) = true
  and p.is_profile_complete = true
  and p.is_public_searchable = true
  and p.is_active = true
  and p.is_approved = true
group by
  u.id,
  u.first_name,
  u.last_name,
  u.profile_photo_url,
  u.bio,
  p.country_code,
  p.location_label,
  p.mapbox_id,
  p.latitude,
  p.longitude,
  p.offers_remote,
  p.offers_in_home,
  p.offers_provider_location;

grant select on public.professional_search_cards_enriched to anon, authenticated;
