-- Professional availability: recurring weekly rules + date exceptions.
-- Slot generation runs on the client; server validates bookable times at booking creation.

-- 1) Exception kind enum
create type public.availability_exception_kind as enum (
  'unavailable',
  'available'
);

-- 2) Weekly recurring availability rules
create table public.professional_availability_rules (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  professional_id bigint not null references public.users (id) on delete cascade,
  day_of_week smallint not null,
  start_time time not null,
  end_time time not null,
  constraint availability_rules_day_of_week_check
    check (day_of_week between 1 and 7),
  constraint availability_rules_end_after_start
    check (end_time > start_time)
);

comment on table public.professional_availability_rules is
  'Recurring weekly availability windows (ISO day: 1=Monday … 7=Sunday).';

comment on column public.professional_availability_rules.day_of_week is
  'ISO-8601 weekday: 1=Monday through 7=Sunday.';

create index professional_availability_rules_professional_day_idx
  on public.professional_availability_rules (professional_id, day_of_week);

create unique index professional_availability_rules_unique_window_idx
  on public.professional_availability_rules (professional_id, day_of_week, start_time, end_time);

-- 3) Date-specific exceptions (blocks or extra hours)
create table public.professional_availability_exceptions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  professional_id bigint not null references public.users (id) on delete cascade,
  exception_date date not null,
  kind public.availability_exception_kind not null,
  start_time time,
  end_time time,
  constraint availability_exceptions_times_both_or_neither
    check (
      (start_time is null and end_time is null)
      or (start_time is not null and end_time is not null and end_time > start_time)
    )
);

comment on table public.professional_availability_exceptions is
  'One-off availability overrides: block time or add extra hours on a date.';

create index professional_availability_exceptions_professional_date_idx
  on public.professional_availability_exceptions (professional_id, exception_date);

-- 4) updated_at triggers
create or replace function public.availability_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists professional_availability_rules_set_updated_at on public.professional_availability_rules;
create trigger professional_availability_rules_set_updated_at
  before update on public.professional_availability_rules
  for each row execute function public.availability_set_updated_at();

drop trigger if exists professional_availability_exceptions_set_updated_at on public.professional_availability_exceptions;
create trigger professional_availability_exceptions_set_updated_at
  before update on public.professional_availability_exceptions
  for each row execute function public.availability_set_updated_at();

-- 5) Booking conflict index for scheduled sessions
create index if not exists bookings_professional_scheduled_at_active_idx
  on public.bookings (professional_id, scheduled_at)
  where status in ('pending', 'accepted') and scheduled_at is not null;

-- 6) ISO weekday helper (1=Monday … 7=Sunday)
create or replace function public.iso_day_of_week(p_date date)
returns smallint
language sql
immutable
as $$
  select extract(isodow from p_date)::smallint;
$$;

create or replace function public.availability_slot_is_bookable(
  p_professional_id bigint,
  p_scheduled_at timestamptz,
  p_duration_minutes integer
) returns boolean
language plpgsql
stable
security definer
set search_path = public
set row_security = off
as $$
declare
  v_tz constant text := 'Europe/London';
  v_local timestamp without time zone;
  v_slot_date date;
  v_slot_start time;
  v_slot_end time;
  v_duration integer;
  v_iso_dow smallint;
  v_has_full_day_unavailable boolean;
  v_window record;
  v_fits boolean := false;
begin
  if p_scheduled_at is null then
    return false;
  end if;

  if p_scheduled_at <= now() then
    return false;
  end if;

  v_duration := greatest(coalesce(p_duration_minutes, 60), 1);

  v_local := p_scheduled_at at time zone v_tz;
  v_slot_date := v_local::date;
  v_slot_start := v_local::time;
  v_slot_end := (v_local + (v_duration || ' minutes')::interval)::time;
  v_iso_dow := public.iso_day_of_week(v_slot_date);

  -- Full-day unavailable exception blocks the entire date
  select exists (
    select 1
    from public.professional_availability_exceptions e
    where e.professional_id = p_professional_id
      and e.exception_date = v_slot_date
      and e.kind = 'unavailable'
      and e.start_time is null
      and e.end_time is null
  )
  into v_has_full_day_unavailable;

  if v_has_full_day_unavailable then
    return false;
  end if;

  -- Check weekly rules for this weekday
  for v_window in
    select r.start_time as w_start, r.end_time as w_end
    from public.professional_availability_rules r
    where r.professional_id = p_professional_id
      and r.day_of_week = v_iso_dow
  loop
    if v_slot_start >= v_window.w_start and v_slot_end <= v_window.w_end then
      -- Subtract partial unavailable exceptions overlapping this slot
      if not exists (
        select 1
        from public.professional_availability_exceptions e
        where e.professional_id = p_professional_id
          and e.exception_date = v_slot_date
          and e.kind = 'unavailable'
          and e.start_time is not null
          and e.end_time is not null
          and v_slot_start < e.end_time
          and v_slot_end > e.start_time
      ) then
        v_fits := true;
        exit;
      end if;
    end if;
  end loop;

  if v_fits then
    return true;
  end if;

  -- Check extra availability exceptions on this date
  for v_window in
    select e.start_time as w_start, e.end_time as w_end
    from public.professional_availability_exceptions e
    where e.professional_id = p_professional_id
      and e.exception_date = v_slot_date
      and e.kind = 'available'
  loop
    if v_window.w_start is null and v_window.w_end is null then
      return true;
    end if;
    if v_slot_start >= v_window.w_start and v_slot_end <= v_window.w_end then
      return true;
    end if;
  end loop;

  return false;
end;
$$;

comment on function public.availability_slot_is_bookable(bigint, timestamptz, integer) is
  'True when scheduled_at falls in an effective availability window (Europe/London MVP).';

revoke all on function public.availability_slot_is_bookable(bigint, timestamptz, integer) from public;
grant execute on function public.availability_slot_is_bookable(bigint, timestamptz, integer) to authenticated;

-- 9) Booking overlap check
create or replace function public.booking_scheduled_at_conflicts(
  p_professional_id bigint,
  p_scheduled_at timestamptz,
  p_duration_minutes integer,
  p_exclude_booking_id bigint default null
) returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select exists (
    select 1
    from public.bookings b
    inner join public.services s on s.id = b.service_id
    where b.professional_id = p_professional_id
      and b.status in ('pending', 'accepted')
      and b.scheduled_at is not null
      and (p_exclude_booking_id is null or b.id <> p_exclude_booking_id)
      and tstzrange(
        b.scheduled_at,
        b.scheduled_at + make_interval(mins => greatest(coalesce(s.duration_minutes, 60), 1))
      )
      && tstzrange(
        p_scheduled_at,
        p_scheduled_at + make_interval(mins => greatest(coalesce(p_duration_minutes, 60), 1))
      )
  );
$$;

revoke all on function public.booking_scheduled_at_conflicts(bigint, timestamptz, integer, bigint) from public;
grant execute on function public.booking_scheduled_at_conflicts(bigint, timestamptz, integer, bigint) to authenticated;

-- 10) Extend ensure_messaging_conversation with optional scheduled_at
drop function if exists public.ensure_messaging_conversation(bigint, bigint);

create or replace function public.ensure_messaging_conversation(
  p_professional_id bigint,
  p_service_id bigint,
  p_scheduled_at timestamp with time zone default null
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_client bigint;
  v_conversation_id bigint;
  v_booking_id bigint;
  v_duration integer;
begin
  v_client := public.app_user_id_for_auth();
  if v_client is null then
    raise exception 'Not authenticated';
  end if;

  if v_client = p_professional_id then
    raise exception 'Cannot start a conversation with yourself';
  end if;

  if not exists (
    select 1
    from public.users u
    where u.id = p_professional_id
      and coalesce(u.is_professional, false) = true
  ) then
    raise exception 'Invalid professional';
  end if;

  if not exists (
    select 1
    from public.services s
    where s.id = p_service_id
      and s.professional_id = p_professional_id
      and s.is_active = true
      and public.is_professional_publicly_listable(s.professional_id)
  ) then
    raise exception 'Invalid service';
  end if;

  select coalesce(s.duration_minutes, 60)
  into v_duration
  from public.services s
  where s.id = p_service_id;

  if p_scheduled_at is not null then
    if not public.availability_slot_is_bookable(p_professional_id, p_scheduled_at, v_duration) then
      raise exception 'Selected time is not available';
    end if;

    if public.booking_scheduled_at_conflicts(p_professional_id, p_scheduled_at, v_duration) then
      raise exception 'Selected time conflicts with an existing booking';
    end if;
  end if;

  select c.id
  into v_conversation_id
  from public.conversations c
  inner join public.bookings b on b.id = c.booking_id
  where b.client_id = v_client
    and b.professional_id = p_professional_id
    and b.service_id = p_service_id
    and b.status in ('pending', 'accepted')
  limit 1;

  if v_conversation_id is not null then
    return v_conversation_id;
  end if;

  begin
    insert into public.bookings (client_id, professional_id, service_id, status, scheduled_at)
    values (v_client, p_professional_id, p_service_id, 'pending', p_scheduled_at)
    returning id into v_booking_id;
  exception
    when unique_violation then
      select c.id
      into v_conversation_id
      from public.conversations c
      inner join public.bookings b on b.id = c.booking_id
      where b.client_id = v_client
        and b.professional_id = p_professional_id
        and b.service_id = p_service_id
        and b.status in ('pending', 'accepted')
      limit 1;
      if v_conversation_id is not null then
        return v_conversation_id;
      end if;
      raise;
  end;

  insert into public.conversations (booking_id)
  values (v_booking_id)
  returning id into v_conversation_id;

  return v_conversation_id;
end;
$$;

comment on function public.ensure_messaging_conversation(bigint, bigint, timestamp with time zone) is
  'Creates or returns existing conversation for (client, professional, service) with an active booking. Optional scheduled_at on new bookings.';

revoke all on function public.ensure_messaging_conversation(bigint, bigint, timestamp with time zone) from public;
grant execute on function public.ensure_messaging_conversation(bigint, bigint, timestamp with time zone) to authenticated;

-- 11) RLS
alter table public.professional_availability_rules enable row level security;
alter table public.professional_availability_exceptions enable row level security;

drop policy if exists "availability_rules_select_own" on public.professional_availability_rules;
create policy "availability_rules_select_own"
  on public.professional_availability_rules
  for select
  to authenticated
  using (professional_id = public.app_user_id_for_auth());

drop policy if exists "availability_rules_select_public" on public.professional_availability_rules;
create policy "availability_rules_select_public"
  on public.professional_availability_rules
  for select
  to authenticated
  using (public.is_professional_publicly_listable(professional_id));

drop policy if exists "availability_rules_insert_own" on public.professional_availability_rules;
create policy "availability_rules_insert_own"
  on public.professional_availability_rules
  for insert
  to authenticated
  with check (
    professional_id = public.app_user_id_for_auth()
    and coalesce(
      (select u.is_professional from public.users u where u.id = public.app_user_id_for_auth()),
      false
    ) = true
  );

drop policy if exists "availability_rules_update_own" on public.professional_availability_rules;
drop policy if exists "availability_rules_update_own_mutation" on public.professional_availability_rules;
create policy "availability_rules_update_own"
  on public.professional_availability_rules
  for update
  to authenticated
  using (professional_id = public.app_user_id_for_auth())
  with check (professional_id = public.app_user_id_for_auth());

drop policy if exists "availability_rules_delete_own" on public.professional_availability_rules;
create policy "availability_rules_delete_own"
  on public.professional_availability_rules
  for delete
  to authenticated
  using (professional_id = public.app_user_id_for_auth());

drop policy if exists "availability_exceptions_select_own" on public.professional_availability_exceptions;
create policy "availability_exceptions_select_own"
  on public.professional_availability_exceptions
  for select
  to authenticated
  using (professional_id = public.app_user_id_for_auth());

drop policy if exists "availability_exceptions_select_public" on public.professional_availability_exceptions;
create policy "availability_exceptions_select_public"
  on public.professional_availability_exceptions
  for select
  to authenticated
  using (public.is_professional_publicly_listable(professional_id));

drop policy if exists "availability_exceptions_insert_own" on public.professional_availability_exceptions;
create policy "availability_exceptions_insert_own"
  on public.professional_availability_exceptions
  for insert
  to authenticated
  with check (
    professional_id = public.app_user_id_for_auth()
    and coalesce(
      (select u.is_professional from public.users u where u.id = public.app_user_id_for_auth()),
      false
    ) = true
  );

drop policy if exists "availability_exceptions_update_own" on public.professional_availability_exceptions;
drop policy if exists "availability_exceptions_update_own_mutation" on public.professional_availability_exceptions;
create policy "availability_exceptions_update_own"
  on public.professional_availability_exceptions
  for update
  to authenticated
  using (professional_id = public.app_user_id_for_auth())
  with check (professional_id = public.app_user_id_for_auth());

drop policy if exists "availability_exceptions_delete_own" on public.professional_availability_exceptions;
create policy "availability_exceptions_delete_own"
  on public.professional_availability_exceptions
  for delete
  to authenticated
  using (professional_id = public.app_user_id_for_auth());

grant select, insert, update, delete on table public.professional_availability_rules to authenticated;
grant select, insert, update, delete on table public.professional_availability_exceptions to authenticated;
