-- Search schema expansion: profile location fields, normalized specialties,
-- public-search policies, and enriched search view.

-- 1) Extend public.users with search/profile fields.
alter table public.users
  add column if not exists is_public_searchable boolean not null default false,
  add column if not exists country_code text,
  add column if not exists location_locality text,
  add column if not exists location_region text,
  add column if not exists postal_code text,
  add column if not exists service_area text,
  add column if not exists rating_avg numeric(3,2) not null default 0,
  add column if not exists rating_count integer not null default 0;

-- If older city column exists, migrate values into locality.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'users'
      and column_name = 'location_city'
  ) then
    execute 'update public.users
             set location_locality = coalesce(location_locality, location_city)
             where location_city is not null';
    execute 'alter table public.users drop column if exists location_city';
  end if;
end $$;

-- Backfill country code before enforcing NOT NULL.
update public.users
set country_code = coalesce(nullif(trim(country_code), ''), 'NG')
where country_code is null
   or trim(country_code) = '';

alter table public.users
  alter column country_code set not null;

alter table public.users
  add constraint users_rating_avg_range
  check (rating_avg >= 0 and rating_avg <= 5);

alter table public.users
  add constraint users_rating_count_non_negative
  check (rating_count >= 0);

-- 2) Create normalized specialty and review tables.
create table if not exists public.specialties (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label text not null,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.professional_specialties (
  professional_id bigint not null references public.users(id) on delete cascade,
  specialty_id bigint not null references public.specialties(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  constraint professional_specialties_pkey primary key (professional_id, specialty_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  professional_id bigint not null references public.users(id) on delete cascade,
  reviewer_id bigint references public.users(id) on delete set null,
  rating smallint not null check (rating between 1 and 5),
  review_text text,
  created_at timestamp with time zone not null default now()
);

-- 3) Add indexes for search/filter paths.
create index if not exists users_public_search_location_idx
  on public.users (country_code, location_locality, location_region)
  where is_professional = true
    and is_profile_complete = true
    and is_searchable = true
    and is_public_searchable = true;

create index if not exists professional_specialties_professional_idx
  on public.professional_specialties (professional_id);

create index if not exists professional_specialties_specialty_idx
  on public.professional_specialties (specialty_id);

create index if not exists reviews_professional_created_at_idx
  on public.reviews (professional_id, created_at desc);

-- 4) RLS + policies.
alter table public.users enable row level security;
alter table public.specialties enable row level security;
alter table public.professional_specialties enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "users_select_public_searchable" on public.users;
create policy "users_select_public_searchable"
  on public.users
  for select
  to anon, authenticated
  using (
    is_professional = true
    and is_profile_complete = true
    and is_searchable = true
    and is_public_searchable = true
  );

drop policy if exists "specialties_read_all" on public.specialties;
create policy "specialties_read_all"
  on public.specialties
  for select
  to anon, authenticated
  using (true);

drop policy if exists "professional_specialties_read_all" on public.professional_specialties;
create policy "professional_specialties_read_all"
  on public.professional_specialties
  for select
  to anon, authenticated
  using (true);

-- Leave review write policies for a future PR; only authenticated users can read for now.
drop policy if exists "reviews_read_authenticated" on public.reviews;
create policy "reviews_read_authenticated"
  on public.reviews
  for select
  to authenticated
  using (true);

grant select on public.users to anon, authenticated;
grant select on public.specialties to anon, authenticated;
grant select on public.professional_specialties to anon, authenticated;
grant select on public.reviews to authenticated;

-- 5) Backfill specialties from legacy users.specialty JSON then remove legacy column.
with parsed_specialties as (
  select
    u.id as professional_id,
    lower(trim(v.value)) as raw_specialty
  from public.users u
  cross join lateral (
    select nullif(trim(value), '') as value
    from (
      -- scalar string specialty
      select
        case
          when u.specialty is null then null
          when jsonb_typeof(u.specialty::jsonb) = 'string'
            then trim(both '"' from u.specialty::text)
          when jsonb_typeof(u.specialty::jsonb) = 'object'
            then coalesce(
              nullif(trim(u.specialty::jsonb ->> 'slug'), ''),
              nullif(trim(u.specialty::jsonb ->> 'label'), ''),
              nullif(trim(u.specialty::jsonb ->> 'name'), '')
            )
          else null
        end as value
      union all
      -- array specialty entries
      select arr.value
      from jsonb_array_elements_text(
        case
          when u.specialty is not null and jsonb_typeof(u.specialty::jsonb) = 'array'
            then u.specialty::jsonb
          else '[]'::jsonb
        end
      ) as arr(value)
    ) parsed
  ) v
  where v.value is not null
),
normalized_specialties as (
  select
    professional_id,
    trim(both '-' from regexp_replace(raw_specialty, '[^a-z0-9]+', '-', 'g')) as slug
  from parsed_specialties
)
insert into public.specialties (slug, label)
select distinct
  slug,
  initcap(replace(slug, '-', ' '))
from normalized_specialties
where slug <> ''
on conflict (slug) do nothing;

with parsed_specialties as (
  select
    u.id as professional_id,
    lower(trim(v.value)) as raw_specialty
  from public.users u
  cross join lateral (
    select nullif(trim(value), '') as value
    from (
      select
        case
          when u.specialty is null then null
          when jsonb_typeof(u.specialty::jsonb) = 'string'
            then trim(both '"' from u.specialty::text)
          when jsonb_typeof(u.specialty::jsonb) = 'object'
            then coalesce(
              nullif(trim(u.specialty::jsonb ->> 'slug'), ''),
              nullif(trim(u.specialty::jsonb ->> 'label'), ''),
              nullif(trim(u.specialty::jsonb ->> 'name'), '')
            )
          else null
        end as value
      union all
      select arr.value
      from jsonb_array_elements_text(
        case
          when u.specialty is not null and jsonb_typeof(u.specialty::jsonb) = 'array'
            then u.specialty::jsonb
          else '[]'::jsonb
        end
      ) as arr(value)
    ) parsed
  ) v
  where v.value is not null
),
normalized_specialties as (
  select
    professional_id,
    trim(both '-' from regexp_replace(raw_specialty, '[^a-z0-9]+', '-', 'g')) as slug
  from parsed_specialties
)
insert into public.professional_specialties (professional_id, specialty_id)
select distinct
  n.professional_id,
  s.id as specialty_id
from normalized_specialties n
join public.specialties s on s.slug = n.slug
where n.slug <> ''
on conflict (professional_id, specialty_id) do nothing;

alter table public.users
  drop column if exists specialty;

-- 6) Enriched search view (no availability projection in this phase).
create or replace view public.professional_search_cards_enriched
with (security_invoker = true) as
select
  u.id as professional_id,
  u.first_name,
  u.last_name,
  u.profile_photo_url,
  u.bio,
  u.country_code,
  u.location_locality,
  u.location_region,
  u.postal_code,
  u.service_area,
  u.rating_avg,
  u.rating_count,
  coalesce(
    array_agg(distinct s.label) filter (where s.label is not null),
    array[]::text[]
  ) as specialties
from public.users u
left join public.professional_specialties ps
  on ps.professional_id = u.id
left join public.specialties s
  on s.id = ps.specialty_id
where u.is_professional = true
  and u.is_profile_complete = true
  and u.is_searchable = true
  and u.is_public_searchable = true
group by
  u.id,
  u.first_name,
  u.last_name,
  u.profile_photo_url,
  u.bio,
  u.country_code,
  u.location_locality,
  u.location_region,
  u.postal_code,
  u.service_area,
  u.rating_avg,
  u.rating_count;

grant select on public.professional_search_cards_enriched to anon, authenticated;
